### ISSUE TITLE
multi-version R and RCall

### ISSUE THREAD

**Issue by armgong** [JuliaStats/RCall.jl#100]
in current version there is no simple way to change R install path in RCall , (except export R_HOME in env before using RCall).
should  add RCall function to select different R version in different path?

**Comment by simonbyrne** [comment]
Unfortunately, at the moment we don't have a great way to pass options to packages, and since the library path is a `const`, this would make it difficult to do in an efficient manner.

**Comment by armgong** [comment]
how about add  a function R_init (like jl_init function in Julia ) which need call by user, and remove initialization  works from Rcall package _init_ function to it?

**Comment by simonbyrne** [comment]
This would be quite complicated in the current setup, and so is not something we'll be doing in the foreseeable future. If you can give a compelling use case (or are willing to fund development), we may reconsider.

As a workaround, one approach would be to have multiple RCall installations, and set the `JULIA_PKGDIR` accordingly.

**Comment by simonbyrne** [comment]
Ah, is this for the `rjulia2` stuff?
