### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#101]
It would be great if there was some tutorial, documentation or example somewhere. Right now I have no clue how to use this. There used to be some documentation, but that seems all gone. The official documentation seems to have an installation section (useful), but no "how do you use this". If there were some simple examples (i.e. IJulia notebooks that show a plot or just anything) that would also work.

**Comment by randy3k** [comment]
The original documentation of RCall is removed as it is outdated and no longer relevant after series of updates. 

The documentation is now generated by [Documenter.jl](http://michaelhatherly.github.io/Documenter.jl).
Examples could be written by utilizing the example feature of [Documenter.jl](http://michaelhatherly.github.io/Documenter.jl/latest/man/syntax/#{example}-1).

**Comment by davidanthoff** [comment]
Fixed by #105. Thanks, this is great!
