### ISSUE TITLE
ccall could not find R_checkActivity

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#104]
I get the following error on Windows with the master version of RCall:

````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using RCall

julia> x = randn(100);

julia> using DataFrames

julia> df = DataFrame(x=x, y=[x[1:50];2x[51:100]] + 0.1randn(100), tp=[zeros(Int,50), ones(Int, 50)]);
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at abstractarray.jl:29
 in vect at abstractarray.jl:32
while loading no file, in expression starting on line 0

julia> @rput df;

julia> @rlibrary ggplot2
WARNING: RCall.jl Need help? Try the ggplot2 mailing list:
http://groups.google.com/group/ggplot2.

julia> reval(rparse("qplot(x, y, data = df, color = factor(tp))"))
RCall.RObject{RCall.VecSxp}

ERROR (unhandled task failure): ccall: could not find function R_checkActivity in library C:\Program Files\R\R-3.2.5\bin\x64\R
 in process_events at C:\Users\anthoff\.julia\v0.4\RCall\src\eventloop.jl:7

julia>
````

**Comment by simonbyrne** [comment]
@randy3k Any ideas what is going on here?

**Comment by simonbyrne** [comment]
Have you recently updated R? Maybe try `Base.compilecache("RCall")` and see if that helps?

**Comment by davidanthoff** [comment]
I should say that the code actually produces the plot, but then this error pops up. So this is not a problem that RCall.jl doesn't find R in the first place.

``Base.compilecache("RCall")`` doesn't help.

I looked at the exported functions in R.dll with DLL Export Viewer, and there simply isn't one that is called ``R_checkActivity``. I'm using R 3.2.5, x64 version.

**Comment by randy3k** [comment]
It looks like that we only need to do `R_ProcessEvents` on Windows machine, at least it is what [RStudio](https://github.com/rstudio/rstudio/blob/ebb054efe3e650de818a251b11087311e5169ed8/src/cpp/r/session/REmbeddedWin32.cpp#L265) does for processing events.

**Comment by davidanthoff** [comment]
Excellent, thanks for the fast turnaround! Any chance you could also tag a release?
