### ISSUE TITLE
Error transferring vectors

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#107]
I'm not sure whether the title is a good error description. I'm trying this:

````
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using RCall

julia> R"library(ggplot2)";

julia> x = randn(100);

julia> y = randn(100);

julia> R"qplot($x,$y)"
RCall.RObject{RCall.VecSxp}
Error showing value of type RCall.RObject{RCall.VecSxp}:
ERROR: RCall.jl Error in eval(expr, envir, enclos) : object '##RCall##1' not found

 in error at error.jl:22
````
Shouldn't that work?

**Comment by randy3k** [comment]
It is due to a bug in RCall, the following should work.
```julia
R"print(qplot($x,$y))"
```

@simonbyrn
It seems that this issue affects all S3 objects with custom print method. `@R_str` has removed the variable before the `rprint` command is invoked.

**Comment by randy3k** [comment]
Look like we need to preserve the variables `##RCall##{number}` until the result returned by `@R_str` has been gc'ed.

**Comment by randy3k** [comment]
the previous fix is not correct, reopen the issue.

**Comment by randy3k** [comment]
#110 should fix it. Please let us know if problem persists.

**Comment by davidanthoff** [comment]
It all works with the latest master, thanks a lot!

One minor thing: the axis labels now are ``$x`` and ``$``, i.e. they include the escape character. Might be nicer if the R variables used just had the julia name variables, without the ``$``?

**Comment by randy3k** [comment]
I think the reason of such implementation is to differentiate R expressions and Julia expressions.

It is possible to pass Julia expressions in `R_str`.
```julia
x = rand(10); # "x" in Julia
globalEnv[:x] = rand(10); # "x" in R
R"plot(x, $x)";
```

**Comment by simonbyrne** [comment]
It was to avoid conflict with R variables (technically, they can conflict anyway, as you can name R variables anything by quoting them with backticks, but this is a rarely used feature). This seemed like the best compromise (hey, it's better than `##RCall##1`).
