### ISSUE TITLE
REPL mode

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#115]
Would be really cool if there was a REPL mode that essentially wrapped the ``R"..."`` macro.

**Comment by randy3k** [comment]
It is certainly cool. A good place to start from https://github.com/JuliaLang/julia/blob/master/test/repl.jl

However, I think that it should be housed in a separated repo `RRepl.jl`.

**Comment by davidanthoff** [comment]
> However, I think that it should be housed in a separated repo RRepl.jl.

Why? Wouldn't it just make it more complicated to find it?

**Comment by randy3k** [comment]
In such way, users can choose to load or do not load the REPL related code.

**Comment by simonbyrne** [comment]
This would be great: if someone wants to take this up, a good place to look would be Kenos's work on Cxx.jl and Gallium.jl, which both implement REPL modes.

I don't think it should be too much overhead such that it would need a separate repo.

**Comment by armgong** [comment]
yes, this is really cool if we have R REPL in RCall.
I alread implement an julia REPL in R when embedding julia with R ,it only need modify R REPL source and load Julia REPL in right place.

**Comment by randy3k** [comment]
tested #115 on Mac 10.10 with julia 0.4.5 and 0.5.
