### ISSUE TITLE
Enable variable splatting support in REPL

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#121]
I am aware that this is tricky, but maybe this issue here can serve as a discussion place on how to achieve this.

@simonbyrne wrote this in #117:
> One idea that has occurred to me is that the R"" macro could evaluate in the global environment, but the substituted variables could be in a macro-specific environment.

Maybe that is a starting point?

**Comment by simonbyrne** [comment]
See https://github.com/JuliaStats/RCall.jl/tree/sb/global-rstr for something I was playing around with, but we still hit the problem of when to clean up the env.

**Comment by randy3k** [comment]
I don't understand why the old `#JL` is not gc'ed...

```julia
julia> using RCall

julia> x = 1:10^8
1:100000000

julia> R"$x + 1"; gc()

R> gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells    224017   12.0     460000   24.6    350000   18.7
Vcells 150415502 1147.6  217000570 1655.6 150416290 1147.6

julia> R"$x + 1"; gc()

R> gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells    224101   12.0     460000   24.6    350000   18.7
Vcells 250415624 1910.6  361000966 2754.3 250415617 1910.6

julia> R"$x + 1"; gc()

R> gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells    224103   12.0     460000   24.6    350000   18.7
Vcells 350415624 2673.5  520017390 3967.5 350415617 2673.5
```

PS: I think you forget to `protect` and `unprotect` the `env` variable.

**Comment by simonbyrne** [comment]
No idea: if someone can figure this out I would be grateful.

**Comment by randy3k** [comment]
Lol. it is not caused by `#JL`

```julia

julia> using RCall

julia> x = 1:10^8
1:100000000

julia> R"sum($x + 1)"; gc()

R> gc()
           used  (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells   224023  12.0     460000   24.6    350000   18.7
Vcells 50415538 384.7  144613747 1103.4 150416326 1147.6

julia> R"sum($x + 1)"; gc()

R> gc()
           used  (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells   224107  12.0     460000   24.6    350000   18.7
Vcells 50415661 384.7  144614012 1103.4 150416326 1147.6

```

**Comment by randy3k** [comment]
Let me open another thread for this

**Comment by simonbyrne** [comment]
Just open a PR on that branch

**Comment by randy3k** [comment]
given the PR in #124, I will start working on the variable substitution in REPL.

**Comment by davidanthoff** [comment]
Now that this is all working, maybe tag a new version, also for juliacon? I seriously think having all this around is a game changer, this is just such a smooth and cool way to interact with R from julia!!

**Comment by randy3k** [comment]
Sure! Juliacon is the reason I spent my last weekend on this...

**Comment by davidanthoff** [comment]
Certainly worth it, the result is really impressive!
