### ISSUE TITLE
deps.jl should be rebuilt when R updates, 

### ISSUE THREAD

**Issue by randy3k** [JuliaStats/RCall.jl#13]
`./deps.jl` should be rebuilt when R is updated, or wrong dylib will be loaded.

https://github.com/randy3k/RCall.jl/blob/8f1f2144b91f146c659009b7364182b40c304f7e/deps/build.jl#L26

**Comment by dmbates** [comment]
All that needs to be done is tor run
```julia
Pkg.build("RCall")
```
when R is updated.  Are you suggesting that this be automated in some way or that the error message when failing to initialize the embedded R be expanded to suggest this possible fix?

**Comment by randy3k** [comment]
Ya, perhaps, it is worth to display an warning message to hint running `Pkg.build("RCall")` when an error is encountered.

**Comment by dmbates** [comment]
Closed by fe181ee3c054acbb32e50afc5cc2d6f2cf77f2d0
