### ISSUE TITLE
Documentation of `Sxp` seems to have the types backwards.

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/RCall.jl#130]
I think it should be

```julia
"""
R symbolic expression (`Sxp`): these are represented by a pointer to a
symbolic expression record (`SxpPtr`).
"""
```

**Comment by randy3k** [comment]
I recall that @simonbyrne tried to name `Sxp` as `SEXPREC` and `SxpPtr` as `SEXP` in early version of RCall.jl to reflect R internal structure. Perhaps `SEXPREC` and `SEXP` are too cumbersome and  difficult to carry or use, therefore we are now using `Sxp` to mirror `SEXPREC` and `SxpPtr` to mirror `SEXP`.

Anyway, the docstring for `Sxp` has updated.
https://github.com/JuliaStats/RCall.jl/commit/5060fbecf7b0db75bece5f164ab17aeefa97b72f
