### ISSUE TITLE
Unicode in R string and R macros

### ISSUE THREAD

**Issue by pochoi** [JuliaStats/RCall.jl#132]
```julia
julia> 🍕 =10
10
 
julia> @rput 🍕
10
 
R> ls()
[1] "#JL"        "\U0001f355" "x"

julia> @rget 🍕
10

julia> R"🍕 +1"
ERROR: Unicode R scripts not supported, due to
     https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16524
in eval(::Module, ::Any) at ./boot.jl:234
in macro expansion at ./REPL.jl:92 [inlined]
in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

If the unicode is prohibited in R string, should it be also prohibited in the R macros?

**Comment by randy3k** [comment]
Actually, the story is more complicated. Not all unicode are not supported.

```julia
julia> α=1
1

julia> @rput α
1

julia> R"α+1"
RCall.RObject{RCall.RealSxp}
[1] 2
```

**Comment by pochoi** [comment]
```julia
julia> α = 1
1

julia> R"$α+1"
ERROR: Unicode R scripts not supported, due to
    https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16524
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
Complicated!

**Comment by randy3k** [comment]
There is a limited support of evaluating R unicode variable, however, substituting unicode julia variable is not supported.

**Comment by simonbyrne** [comment]
This is due to R's broken parser info, and the hackish way in which variable substitution is implemented (by iteratively calling the R parser and checking for errors). If there are no variables to be substituted then we don't need the parser info, so no unicode check is performed.

I see two possible ways to resolve this:
* Fix the R parser issue
* Implement our own R parser

**Comment by randy3k** [comment]
[This](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/gram.c) is the R parser. I tried to understand it, but it is way beyond my ability. The bug is due to `R_ParseErrorCol` not being able to capture the correct column of the parse error.

**Comment by armgong** [comment]
the R parser use YACC, so also need read https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/gram.y

**Comment by randy3k** [comment]
Found a hacky solution of using `R_ParseContextLast` and `R_ParseContext`.

**Comment by randy3k** [comment]
With the new commit, the pizza can be obtained as follows

```julia
julia> 🍕 = 10
10

julia> @rput 🍕
10

R> `🍕`
[1] 10

```
