### ISSUE TITLE
ASCIIString Array conversion error

### ISSUE THREAD

**Issue by multidis** [JuliaStats/RCall.jl#16]
sexp("q")
    SEXP{16}(Ptr{Void} @0x000000000ea8f988)

    sexp(["p", "q"])
    ERROR: `sexp` has no method matching sexp(::Array{ASCIIString,1})

Would be helpful to convert string vectors as well. Here is an [example](https://gist.github.com/multidis/7ac6f4779e09c986be39) of my attempts to convert DataFrame to R object where this limitation shows up, as a part of this [discussion](https://groups.google.com/forum/#!topic/julia-users/8BwPQxbOWV8/discussion).

PS: Thanks for the very helpful package!

**Comment by dmbates** [comment]
It was an oversight that there is no `sexp` method for `Vector{ASCIIString}`.  I will add such a method.
