### ISSUE TITLE
Copy the contents of an R object to Julia instead of protecting it?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/RCall.jl#21]
At present the `vec` methods preserve the R storage using `R_PreserveObject`.  If `vec` is called frequently then garbage collection of the Julia objects becomes slow because `R_ReleaseObject` does a linear search on a long vector.

One way around this is to have the evaluation of a name or expression create the appropriate Julia object and copy the contents of the R object into Julia storage.  This seems like a good idea to me right now but I may have missed good reasons to keep things as they are.

Opinions?

**Comment by simonbyrne** [comment]
Hopefully this has now been addressed with #59
