### ISSUE TITLE
Getting RCall passing on PkgEval

### ISSUE THREAD

**Issue by IainNZ** [JuliaStats/RCall.jl#25]
Hi @dmbates,

With the recent PackageEvaluator rework I think its not only reasonable but possible to support R-based packages like RCall.

Currently RCall is failing its tests:
http://pkg.julialang.org/?pkg=RCall&ver=release

I am installing R:
https://github.com/IainNZ/PackageEvaluator.jl/blob/1428070377795d2b3977e8f768633f862d0c6138/scripts/setup.sh#L71-L72

But I'm wondering if maybe its too old a version?

**Comment by dmbates** [comment]
It is a matter of the version in part but more a problem of a badly designed test. That check is on the number of datasets in a particular R package, which can change between versions. I will change the test to something more reasonable.

Thanks for looking into this.

**Comment by dmbates** [comment]
I have modified the test that was failing so that it no longer depends on the version of R being used.

@IainNZ Can you rerun the PkgEval check or do you want me to commit a new release to trigger the recheck?

**Comment by IainNZ** [comment]
PkgEval runs only again release versions of packages, so once you tag a new version it should eventually update when a successful run completes

**Comment by dmbates** [comment]
I think that RCall-0.1.1 which @andreasnoack was kind enough to publish, should pass this test.

**Comment by IainNZ** [comment]
Passing now!
