### ISSUE TITLE
NA values are not handled probably

### ISSUE THREAD

**Issue by randy3k** [JuliaStats/RCall.jl#32]
```
julia> DataArray(reval("c(NA,1)"))
2-element DataArray{Float64,1}:
 NaN  
   1.0
```
the correct result should be similar to
```
julia> @data([NA,1.0])
2-element DataArray{Float64,1}:
  NA
 1.0
```

Error is reported when converting a vector of string containing NA.
```
julia> DataArray(reval("c(NA,'a')"))
ERROR: `bytestring` has no method matching bytestring(::CharSxp)
 in isNA at /Users/Randy/.julia/v0.3/RCall/src/sexp.jl:148
 in DataArray at /Users/Randy/.julia/v0.3/RCall/src/sexp.jl:150
```

**Comment by dmbates** [comment]
I think there are two issues here: recognizing the NA value for Float64 and recognizing it for CharSxp.

**Comment by dmbates** [comment]
I realized what the problem with the Float64 vectors is.  I used == on Float64 values to check if it matches R_NaReal but equality comparisons don't return true for Float64 values that correspond to NaNs.  I changed the comparison to === and also fixed the isNA method for Complex128

**Comment by randy3k** [comment]
With me last PR #34, there is still a bug: not handling 'NA' and NA correctly.

```
julia> DataArray(reval("c(NA,'NA','foo')"))
3-element DataArray{ASCIIString,1}:
 NA   
 NA   
 "foo"
```

**Comment by randy3k** [comment]
31fa1fe6c88998c8035aba13b6c442252556a80f fixes.
