### ISSUE TITLE
datasets should not be converted to LangSxp's by @rimport

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/RCall.jl#33]
Currently all the objects in an R package are converted to `LangSxp`'s by `@rimport`, which is not appropriate for R objects that are vectors, in the R sense.  There should at least be a check on whether the name evaluates to a CLOSXP before conversion.  I'll take a look at this.
```
julia> using RCall

julia> @rimport MASS as m

julia> typeof m.s
sammon   ships     shrimp    snails    steam     stormer   survey    synth.tr
select   shoes     shuttle   stdres    stepAIC   studres   synth.te
julia> typeof(m.shuttle)
LangSxp (constructor with 2 methods)

julia> rcall(m.shuttle)
Error: attempt to apply non-function
ERROR: Error occurred in R_tryEval
 in reval at /home/bates/.julia/v0.3/RCall/src/iface.jl:5
 in reval at /home/bates/.julia/v0.3/RCall/src/iface.jl:16

```

**Comment by dmbates** [comment]
@randy3k I am trying to work out the logic of the rwrap function.  Is it based on a function in PyCall?

For example, is there a reason for looking at the package as an environment and calling the R ls function on the environment rather than just creating an R call to `ls('package:$pkg')`.  Are you trying to access unexported symbols in the R package?

**Comment by randy3k** [comment]
@dmbates in some sense, it is based on a function in PyCall but being tailed made for our use.
`rwrap` function tries to export all contents of a package by a `LangSxp` label. The `LangSxp` label can then be evaluated to return the actual content.

```
julia> rprint(m.shuttle)
MASS::shuttle

julia> reval(m.shuttle)
VecSxp(-2147483469,Ptr{Void} @0x00007ff0a6260750,Ptr{Void} @0x00007ff0a679ebb0,Ptr{Ptr{None}} @0x00007ff0a679ebd8,7,0)
```

the first argument of `rcall` should be a `RFunction`, `LangSxp`, `SymSxp` or `Symbol`, for example, your could do

```
julia> rcall(:dim, m.shuttle)
IntSxp(536870925,Ptr{Void} @0x00007ff0a683db78,Ptr{Void} @0x00007ff0a1190a88,Ptr{Int32} @0x00007ff0a1190ab0,2,0)
```

**Comment by randy3k** [comment]
RCall has undergone a huge upgrade, this old thread is closed now.
