### ISSUE TITLE
travis ci testing

### ISSUE THREAD

**Issue by randy3k** [JuliaStats/RCall.jl#38]
Is there any reason for not turning on the travis ci testing service? It would be very helpful in checking if a PR is valid.

**Comment by dmbates** [comment]
It would be a matter of writing a .travis.yml script to install both Julia and R.  The typical travis script for a Julia package does not provide R

**Comment by randy3k** [comment]
The .travis of [Rcalling.jl](https://github.com/randy3k/RCalling.jl/blob/master/.travis.yml) or (Rif.jl)[https://github.com/lgautier/Rif.jl/blob/master/.travis.yml] will do the job.

**Comment by dmbates** [comment]
I looked at the Rif.jl travis script.  I would use r-recommended rather than r-base.  r-recommended provides all the recommended packages, such as MASS.

@randy3k Are you able to make commits to this repository directly?  I would be fine with you doing that instead of needing to submit PR's.

**Comment by dmbates** [comment]
@randy3k  I think you have responded to the invitation to join the Rinterfaces team. You should now have write access to the repository.  Let me know if it works.

**Comment by randy3k** [comment]
I will try to see how it works. Thanks for the invitation though.

**Comment by randy3k** [comment]
@dmbates I have just pushed a new `.travis.yml`.
The [test](https://travis-ci.org/JuliaStats/RCall.jl) didn't start automatically. I believe that somebody has to log in travis-ci and enable the service for this repo. Do you know who is probably in charge of this?

**Comment by simonbyrne** [comment]
I've switched on travis testing, and it now seems to be working.

**Comment by simonbyrne** [comment]
I've only enabled release testing, as nightly throws a lot of errors. To enable it, just uncomment the relevant line in `.travis.yml`.
