### ISSUE TITLE
Error in plot.new() : the base graphics system is not registered

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/RCall.jl#47]
Okay, another weird graphics bug. Certain unrelated julia functions will trigger the following error when an R graphics function is subsequently called
```
Error in plot.new() : the base graphics system is not registered
```

The following reliably triggers it on the second invocation of `plot(1:10)` on my system (OS X, v0.3.7) when run at the REPL (though seems fine when in a script, or via `include`).

```julia
using RCall

rprint("png('/tmp/aa.png')")
rprint("plot(1:10)")
rprint("dev.off()")

io = IOBuffer()
write(io,"1,2,3")
seek(io,0)
readall(io) # this seems to be the trigger

rprint("png('/tmp/aa.png')")
rprint("plot(1:10)")
rprint("dev.off()")
```

**Comment by simonbyrne** [comment]
Hmm, if I insert a `rprint("gc()")` call in the middle, that seems to fix things. Does this mean it's a memory leak somewhere?

**Comment by panlanfeng** [comment]
The code runs well on my OS X 10.10.3 with Julia 0.3.7, RCall 0.1.2.

**Comment by randy3k** [comment]
I get the message at random. Not sure how to reproduce it. Your code runs well some time but not another.
```
Error in plot.new() : the base graphics system is not registered
```

**Comment by randy3k** [comment]
It is related to the variable `baseRegisterIndex` in C
```
unsafe_load(cglobal((:baseRegisterIndex,RCall.libR),Int32))
```
The normal value of `baseRegisterIndex` should be >=0. However, due to unknown reason, the value was changed to -1, which lead to the error.

A way to change it to -1 that I know of is
```
ccall((:Rf_KillAllDevices,RCall.libR), Int32, ())
```

**Comment by simonbyrne** [comment]
I think the problem may have been that the finalizer was being called prematurely. Hopefully this works correctly now. Please reopen if there are further problems.

**Comment by randy3k** [comment]
Good catch. It should be the reason. As `Rf_endEmbeddedR` calls `Rf_KillAllDevices` which sets `baseRegisterIndex` to -1.

**Comment by simonbyrne** [comment]
Yeah, I guess the crazy nature of the bug should have been a clue it was gc related.
