### ISSUE TITLE
interact with R event loops

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/RCall.jl#49]
In order to get features like graphics windows working correctly, we need to be able to interact with the R event loops. Some details are covered in [R-ext §8](http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-GUIs-and-other-front_002dends-to-R).

From what I understand, we need to implement (some of) the functionality provided by `run_Rmainloop`.

**Comment by randy3k** [comment]
Eventloop was implemented in RCalling.jl and Rif.jl. See for example [this link](https://github.com/randy3k/RCalling.jl/blob/15e38fce6e803773642dc278877d3971234846c2/deps/init.c#L35). The code was written in C, however, it should be easy to port it to Julia. I can submit a PR this afternoon.

**Comment by randy3k** [comment]
Please checkout the current master branch for the eventloop. Basically, there are two functions: `RCall.rgui_start()` and `RCall.rgui_stop()`.

**Comment by simonbyrne** [comment]
Once we have callbacks sorted out, we could automate this using `setHook`.

**Comment by randy3k** [comment]
In the [eventloop](https://github.com/randy3k/RCall.jl/blob/master/src/eventloop.jl#L3), there was a dirty fix related to `sigint`. The problem was when a `sigint` is signaled from Julia (pressing Control - C), the `R_interrupts_pending` is set to state 1. Without a proper R eventloop, `R_interrupts_pending` remains state 1. And it causes segfault when evaluating `R_ProcessEvents`. So `R_interrupts_pending` was forced to be 0 in there.

For a while, I only think that it is needed for `R_ProcessEvents`. Until just now, I discovered this when I pressed a `sigint` somewhere.

```julia
julia> using RCall

julia> reval("gc()")
RCall.RObject{RCall.RealSxp}
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 219236 11.8     460000 24.6   350000 18.7
Vcells 322397  2.5     786432  6.0   786432  6.0


julia> ^C

julia> reval("gc()")
ERROR: RCall.jl 

 in error at error.jl:22
 in reval_p at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:11
 in reval_p at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:19
 in reval at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:29
 in reval at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:31

julia> reval("gc()")

signal (11): Segmentation fault: 11
sexp at /Users/Randy/.julia/v0.4/RCall/src/types.jl:332
jlcall_sexp_21402 at  (unknown line)
reval_p at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:18
reval at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:29
jlcall_reval_21529 at  (unknown line)
reval at /Users/Randy/.julia/v0.4/RCall/src/iface.jl:31
jl_apply at /opt/local/julia/src/interpreter.c:55
eval at /opt/local/julia/src/interpreter.c:213
jl_toplevel_eval_flex at /opt/local/julia/src/toplevel.c:527
jl_toplevel_eval_in at /opt/local/julia/src/builtins.c:579
eval_user_input at REPL.jl:62
jlcall_eval_user_input_21267 at  (unknown line)
anonymous at REPL.jl:92
jl_apply at /opt/local/julia/src/task.c:241
Selection: 
```

But interesting, if `reval("gc()")` is replaced by `rcall(:gc)`, it causes no issues.

**Comment by randy3k** [comment]
One possible solution is to disable signal handling and handling `sigint` manually
```
    if !Rinited
        unsafe_store!(cglobal((:R_SignalHandlers,RCall.libR),Cint),0)
        argv = ["REmbeddedJulia","--silent","--no-save"]
        i = ccall((:Rf_initEmbeddedR,libR),Cint,(Cint,Ptr{Ptr{UInt8}}),length(argv),argv)
        i > 0 || error("initEmbeddedR failed. Try restarting and running Pkg.build(\"RCall\").")
        global const Rproc = Rinstance(i)
    end
```

**Comment by randy3k** [comment]
Though the eventloop implementation is still primitive, I believe this thread could be closed (at least for now).

**Comment by simonbyrne** [comment]
One thought: in the timer loop we could check if there are any open graphics devices, and if not, close the timer?

**Comment by randy3k** [comment]
If I am correct, the timer loop is also needed for some X11 applications and they are not necessary graphics.

**Comment by simonbyrne** [comment]
We could create a graphic-specific one (started by a hook), and a general (manual) one?
