### ISSUE TITLE
Copy arrays from Julia to R

### ISSUE THREAD

**Issue by robertdj** [JuliaStats/RCall.jl#62]
Hi,

Is it possible to copy simple arrays (matrices/vectors) from Julia to R, let R do some work and copy the result back?
In the documentation I have only found examples where R objects are copied to Julia.

**Comment by simonbyrne** [comment]
Yes it is: `sexp(X)` should do the trick at the moment.

I'm in the middle of a major refactor of the package (#59), after which the interface will be `RObject(X)`.

**Comment by robertdj** [comment]
Thanks for your quick reply. How do I access the `X` element after using `sexp`? 

In the following small example I get an error

    using RCall
    x = ones(2)
    sexp(x)
    reval("2*x")

    Error: object 'x' not found
    
(This is using version 3.8, as I'm getting errors with the `show` function on 0.4-dev.)

**Comment by simonbyrne** [comment]
One way would be to write:
```
globalEnv[:x] = sexp(x)
```

**Comment by robertdj** [comment]
It certainly works -- thanks :-)
