### ISSUE TITLE
Display issue when used from IJulia

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/RCall.jl#63]
I open a new notebook, first cell is
````
using RCall
````
Second cell is
````
"x <- 5" |> rcopy
````
This returns an empty graph as the first output, and only then the real output of 
````
1-element Array{Float64,1}:
 5.0
````
If I then add a third cell that has purely julia code, it will also add this empty graph in the out cell. 

I attach a screen shot:

![image](https://cloud.githubusercontent.com/assets/1036561/9366650/728187f8-466d-11e5-99b4-aa1f73e1a50a.png)

I'm on Windows, julia 0.3.11, IPython/Jupyter 3 and all packages updated to the latest version. This happends with RCall from master or the latest registered version.

Any idea?

**Comment by davidanthoff** [comment]
Oh, and I just tried this on the ``sb/robject`` branch, same thing.

**Comment by simonbyrne** [comment]
Thanks, I'll look into it.
