### ISSUE TITLE
changes to eventloop.jl for new Timer never released?

### ISSUE THREAD

**Issue by protogeezer** [JuliaStats/RCall.jl#64]
julia> Pkg.rm("RCall")
INFO: Removing RCall v0.2.1
INFO: Package database updated
It seems that the changes to eventless.jl for the new Timer never got released. The version that is being installed as of a few minutes ago is still v0.2.1... 
======================
julia> Pkg.add("RCall")
INFO: Installing RCall v0.2.1
INFO: Building RCall
INFO: Package database updated

julia> quit()
et-imac-retina:vams sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6916 (2015-08-23 18:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f8c1986* (1 day old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using RCall
ERROR: LoadError: LoadError: Timer(f) is deprecated. Use Timer(f, delay, repeat) instead.
 in call at deprecated.jl:523
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:267
 in require at ./loading.jl:206
while loading /Users/sjbespa/.julia/v0.4/RCall/src/eventloop.jl, in expression starting on line 16
while loading /Users/sjbespa/.julia/v0.4/RCall/src/RCall.jl, in expression starting on line 77

**Comment by simonbyrne** [comment]
The dependencies are broken on 0.4 at the moment anyway. My aim is to have a new version tagged by the time 0.4 is released, which will fix this issue. 

You can either work on `master` (and try out the new interface: all feedback welcome), or manually checkout c1ff136864964cf2ac04b679f0c1b3b243df7e37, which should include the fix.

**Comment by datnamer** [comment]
@simonbyrne can you provide a quick high level minimal example using the new API?

**Comment by simonbyrne** [comment]
1. Use `RObject` instead of `sexp` to convert a julia object to an R one: e.g. `x = RObject(randn(10))`
2. Use `rcopy` to convert an R object to a julia one.
3. `@rput` to copy a julia variable to the R one of the same name
4. `@rget` to copy an R variable to a julia one of the same name
