### ISSUE TITLE
using RCall changes Pkg.dir() on Windows

### ISSUE THREAD

**Issue by AndyGreenwell** [JuliaStats/RCall.jl#68]
While working against the current master for RCall (obtained via `Pkg.checkout("RCall")`), when executing:

`using RCall`

from within a either a 32-bit or a 64-bit Julia session on Windows, the value assigned to `Pkg.dir()` is currently being modified.

This behavior creates problems when attempting to load other packages later in the same Julia session.

Below is an example Julia session:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7067 (2015-08-28 17:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e82ba0c (11 days old master)
|__/                   |  i686-w64-mingw32

julia> Pkg.dir()
"C:\\Users\\Administrator\\.julia\\v0.4"

julia> using RCall

julia> Pkg.dir()
"C:\\Users\\Administrator\\Documents\\.julia\\v0.4"

julia>
```

**Comment by simonbyrne** [comment]
Does that fix it?

**Comment by AndyGreenwell** [comment]
At present, that [check-in](https://github.com/JuliaStats/RCall.jl/commit/95cd4b55d762aeb9f9c84d625b62d43dc22204ac) did not change the behavior on my machine.  The following were the steps I performed to test this check-in on my existing machine image (I will also set up a fresh operating system image and Julia installation as well):

* Deleted the "RCall" folder from both the `C:\Users\<username>\.julia\v0.4` and `C:\Users\<username>\.julia\.cache` directories.
* Launched Julia v0.4-pre build
* Performed a `Pkg.update()`
* Performed a `Pkg.checkout("RCall")`
* Closed Julia
* Launched Julia again
* Performed a `Pkg.dir()` operation as above
* Performed a `using RCall` operation as above
* Performed a second `Pkg.dir()` operation as above

The returned directories for each of the `Pkg.dir()` operations are currently the same as shown above, with the second call having the modified directory.

**Comment by simonbyrne** [comment]
Sorry, can you try:
```
Pkg.checkout("RCall","master")
Pkg.build("RCall")
```

**Comment by AndyGreenwell** [comment]
In performing the following:
* installed a new 32-bit Windows 8.1 VM
* installed a Julia v0.4.0-rc1 build
* installed [R from CRAN](https://cran.r-project.org/bin/windows/base/)
* Manually added "C:\Program Files\R\R-3.2.2\bin" to the system's Path environment variable.
* launched Julia
* `Pkg.add("RCall")`
* `Pkg.checkout("RCall","master")`
* `Pkg.build("RCall")`
* restarted Julia
* `Pkg.dir()`
* `using RCall`
* `Pkg.dir()`

the output from the two calls to `Pkg.dir()` provided the correct location of `C:\Users\<username>\.julia\v0.4`

**Comment by simonbyrne** [comment]
Great. Once I tag a release we should be able to get rid of some of those steps...

You also shouldn't have to manually modify the PATH variable (the build process looks up the windows registry to find the installation path).

**Comment by AndyGreenwell** [comment]
I tried executing `using RCall` before having set the PATH variable and an error was thrown due to not finding the R.dll.  After adding the directory containing R.exe and Rscript.exe to the PATH, the above steps worked as hoped.  I will repeat the installation steps without having manually modified the PATH to test again.

**Comment by simonbyrne** [comment]
Hmm, I see. You may have to close and reopen Julia before running `Pkg.build`?

I'll see what I can do to make the steps easier.
