### ISSUE TITLE
need to `PreserveObject` when calling `rawvector`?

### ISSUE THREAD

**Issue by randy3k** [JuliaStats/RCall.jl#7]
follow up #6 
When a R memory is referenced by a julia variable, It may be always necessary to execute `PreserveObject` when `rawvector` is called.

**Comment by dmbates** [comment]
Not quite 'always'.  The R garbage collector is currently a generational mark/sweep design that examines the 'named' field in the sxpinfo 32-bit word at the beginning of an SEXPREC.  A value of 0 means that the object is not assigned to a name and is available for garbage collection unless it can be reached from another object.  I'm not clear on the distinction between values of 1 and 2 in that field.

The conservative approach is to call PreserveObject on every value from `rawvector` or to copy the values into Julia objects.  Copying would mean that you couldn't modify the object's value as seen by R, which you may want to do.  Also, it can result in unnecessary storage allocation.  Calling PreserveObject on the value results in its not being available for garbage collection in R and could mean excessive storage allocation.  If PreserveObject were to be called then the Julia object should have a finalizer that calles ReleaseObject.

Perhaps it would be best to have a discussion on the julia-stats list regarding the best strategy.  I'll start a thread.

**Comment by randy3k** [comment]
Don't we always need to protect a R object from GC when we expose it to julia? My example in #6 clear shows that it is necessary.

I understand that `PreserveObject ` and `ReleaseObject` should be using as a pair. And that is precisely what Rif.jl and  [RCalling.jl](https://github.com/randy3k/RCalling.jl) are actually doing.

It may not be desirable to call PreserveObject on every element of `rawvector` of a long vector.
From my experience in RCalling.jl, if the number of preserved objects is large, say 100,000. The time to execute the finalizers can takes up to 30 secs, which is of course not acceptable.

It would be beneficial to have a discussion on the julia-stats list.

**Comment by dmbates** [comment]
There can cases where an R object does not need protection, if, for example, you are going to copy it into a Julia object immediately.  If you just want an R dataset you could retrieve it in R and immediately copy the contents to Julia vectors.  Evaluating a symbol in R returns an object that, by definition, has a named field of 2, and hence will not be garbage collected.

**Comment by dmbates** [comment]
See the [julia-stats thread](https://groups.google.com/forum/#!topic/julia-stats/_ksANpKPQSk)

**Comment by dmbates** [comment]
6f529c2
