### ISSUE TITLE
Calling R functions with keyword argumets that have attributes 

### ISSUE THREAD

**Issue by mbeltagy** [JuliaStats/RCall.jl#71]
If I was to call R's [stars](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/stars.html) function. It is easy to invoke it with 
```julia
rprint(rcall(:stars,myDf))
```
However if I try to set the `draw.segments=TRUE` as I would in `R`. The following invocation fails
 ```julia
rprint(rcall(:stars,myDf,draw.segments=true))
ERROR: syntax: keyword argument is not a symbol: "draw.segments"
```
I saw nothing in the documentation to clarify how this might be handled.

**Comment by dmbates** [comment]
I don't think the example is reproducible so I will ask you to try
```julia
rprint(rcall(:stars,myDF;draw.segments=true))
```
to see if that works.  In Julia named arguments are allowed only after the ; separator.

**Comment by simonbyrne** [comment]
actually the separator is only required for definitions, you don't need it for calling

**Comment by mbeltagy** [comment]
I tried it and it did not work. It is same error
```julia
rprint(rcall(:stars,myDf;draw.segments=true))
ERROR: syntax: keyword argument is not a symbol: "draw.segments"
```
The trouble appears to be with `draw.segments`. Julia seems to be having trouble passing it along to R. In Julia, I have never come across keyword arguments with attributes as in R.

**Comment by simonbyrne** [comment]
@mbeltagy I don't yet have a good way to handle that case.

**Comment by randy3k** [comment]
It is one of the way to mimic this, certainly not a good way.
```
eval(:(rcall(:stars,:mtcars,$(symbol("draw.symbol"))=true)))
```

**Comment by mbeltagy** [comment]
It works!
```julia
 eval(:(rcall(:stars,:mtcars,$(symbol("draw.segments"))=true)))
```
The syntax is a bit cumbersome though. I look forward to an `@rcall` macro.

**Comment by simonbyrne** [comment]
A neat hack I once came across somewhere (I don't remember where). Define the following:
```julia
macro var_str(s)
    symbol(s)
end
```
then the following should work:
```
rprint(rcall(:stars,myDF;var"draw.segments"=true))
```

**Comment by simonbyrne** [comment]
I would be okay with incorporating something along these lines. Any suggestions for a good prefix? `r`, `s`, and `v` are all taken by uses in Base (which, unfortunately, are the 3 most relevant in this case).

**Comment by simonbyrne** [comment]
I've added the above macro, so hopefully that is a reasonable solution.
