### ISSUE TITLE
RCall gives error "LoadError: MethodError: `convert` has no method matching convert(::Type{DataFrames.DataFrame}, ::Symbol)

### ISSUE THREAD

**Issue by uozden** [JuliaStats/RCall.jl#78]
Hi,
Thank you for developing the package. 
I have installèd RCall v0.3.1, on Windows 10. I am using Julia ver.0.4.1. 

````
Pkg.add("RCall")
using DataArrays,DataFrames,RCall

attenu = DataFrame(:attenu)

````

which gives error: 

``````
oadError: MethodError: `convert` has no method matching convert(::Type{DataFrames.DataFrame}, ::Symbol)
This may have arisen from a call to the constructor DataFrames.DataFrame(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{DataFrames.DataFrame}, !Matched::Array{T,2})
  convert(::Type{DataFrames.DataFrame}, !Matched::Dict{K,V})
  ...
while loading In[4], in expression starting on line 1

 in call at essentials.jl:56

``````
However,when I typed `rprint(:airmiles)` then the command works, ang gives the answer
`````
Time Series:
Start = 1937 
End = 1960 
Frequency = 1 
 [1]   412   480   683  1052  1385  1418  1634  2178  3362  5948  6109  5981
[13]  6753  8003 10566 12528 14760 16769 19819 22362 25340 25343 29269 30514
``````
 Thank you for your kind help.

**Comment by nalimilan** [comment]
"What did you expect?" :-)

What is `DataFrame(:attenu)` supposed to do? The error means that trying to convert the symbol `:attenu` to a data frame isn't possible, which is quite correct.

I guess you wanted to do this instead:
```julia
using RDatasets
attenu = dataset("datasets", "attenu")
```

(Next time, please use the julia-stats mailing lists for questions, and keep GitHub for actual bugs.)

**Comment by randy3k** [comment]
I guess it is not a problem of RCall, maybe you have an old version of DataFrames? Could you try `Pkg.update()`?

**Comment by nalimilan** [comment]
Doesn't work here either. Is it supposed to?

**Comment by nalimilan** [comment]
A syntax that works is `attenu = rcopy(DataFrame,:attenu)`.

**Comment by uozden** [comment]
Thank you for your kind help. `attenu = rcopy(DataFrame,:attenu)` worked. Excellent job.

**Comment by simonbyrne** [comment]
`DataFrame(:attenu)` was the old usage, I perhaps should have included a deprecation phase but I broke so many things I didn't think it was worth it.
