### ISSUE TITLE
Unable to locate libR.dylib

### ISSUE THREAD

**Issue by rodonn** [JuliaStats/RCall.jl#80]
I have the latest version of R installed via Homebew (homebrew/science/r-3.2.3).
I am on OSX 10.11.1 
I manually set ` ENV["R_HOME"] = "/usr/local/Cellar/r/3.2.3/"`

When I call `Pkg.build("RCall")`
I get the following error
```
LoadError: Unable to locate libR.dylib
Try setting R_HOME, and re-run Pkg.build("RCall").
while loading /Users/rodonn/.julia/v0.4/RCall/deps/build.jl, in expression starting on line 3
```

I tried adding
```
ENV["DYLD_LIBRARY_PATH"] = "/usr/local/Cellar/r/3.2.3/lib"
ENV["LD_LIBRARY_PATH"] = "/usr/local/Cellar/r/3.2.3/lib"
```
but I still get the same error.

Thanks!

**Comment by randy3k** [comment]
Would you try running `Rscript -e "cat(Sys.getenv('R_HOME'))"` in your terminal?

**Comment by rodonn** [comment]
Ok that fixed it. Thanks for your help. Sorry I didn't realize what the correct value for R_HOME should have been "/usr/local/Cellar/r/3.2.3/R.framework/Resources".

**Comment by randy3k** [comment]
Just try to understand what is happening. Are you using the binary distribution on OSX?

**Comment by simonbyrne** [comment]
You shouldn't need to set `R_HOME` at all if you're using the homebrew/science tap. What happens if you run `Pkg.build("RCall")` without having it set?

**Comment by randy3k** [comment]
On OS X, Applications have their PATH set by launchctl, not by the shell. That was why I asked if his Julia in the binary distribution. On OS X, the PATH variable can be obtained by running
```
/usr/bin/login -fpql $USER $SHELL -l -c 'echo -n $PATH'
```

**Comment by randy3k** [comment]
Ah...actually, if `Rscript` is not found, [this](https://github.com/JuliaStats/RCall.jl/blob/a05553f3247d0b53a411f472fd176e0e769824e6/deps/build.jl#L42) line will be erroneous. It wouldn't wait until the [line](https://github.com/JuliaStats/RCall.jl/blob/a05553f3247d0b53a411f472fd176e0e769824e6/deps/build.jl#L46) `LoadError: Unable to locate libR.dylib`.

**Comment by simonbyrne** [comment]
I get the same error if I set `R_HOME` as above: the problem is that R warns that this conflicts with its own:

```julia
julia> ENV["R_HOME"]="/usr/local/Cellar/r/3.2.3/"
"/usr/local/Cellar/r/3.2.3/"

julia> Rscript = joinpath(ENV["R_HOME"],"bin","Rscript")
"/usr/local/Cellar/r/3.2.3/bin/Rscript"

julia> readall(`$Rscript -e "cat(Sys.getenv('R_HOME'))"`)
"WARNING: ignoring environment value of R_HOME\n/usr/local/Cellar/r/3.2.3/R.framework/Resources"
```

**Comment by rodonn** [comment]
I installed R with brew. 
I installed RStudio and julia using brew cask.

The first thing I tried was `Pkg.build("RCall")` without making any modifications to ENV, but I got an error about not being able to find R.

I'm not able to replicate my problem though. Now if I open a fresh session of R and call `Pkg.build("RCall")` it builds correctly without any errors.

**Comment by simonbyrne** [comment]
How did you install Julia (and which version)?

**Comment by simonbyrne** [comment]
The library search logic has been changed. Do reopen though if this is still an issue.
