### ISSUE TITLE
Use of an R_str, or similar, macro?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/RCall.jl#82]
I had been wondering for some time how a string modifier like the `'r`' in `r"my\w+regexp"`was defined and whether we could define `R"x <- seq(0,1,101)"` to mean `reval("x <- seq(0,1,101)")`, say.  It turns out that the magic is defining a macro with the name `R_str`.

Does it seem worthwhile allowing this kind of simplification of calls to `reval(str)` or, perhaps, `rcopy(reval(str))`.  I find that when using the `RCall` package I get tired of writing that sequence of calls over and over.

**Comment by nalimilan** [comment]
Would an `@R` macro work? I suspect many R expressions are also valid Julia syntax, and that way one would benefit from syntax highlighting. Though it certainly makes sense to have a non-standard string literal, in particular if one wants to write several lines of R code using `"""`.

**Comment by randy3k** [comment]
> I suspect many R expressions are also valid Julia syntax, and....

 I can list a number of exceptions

1. list subset `list$abc` and `list[["abc"]]`
2. variable names containing dots, e.g., `obj.num1`
3.  `%*%`, `%%`, `%in%`, etc and user defined operators.
4. assignment `<-` and `<<-`

**Comment by simonbyrne** [comment]
I actually made a start on this on the [`rstr` branch](https://github.com/JuliaStats/RCall.jl/compare/rstr), currently unfinished. The idea was to support `$` substitution whenever the `$` was invalid in R, so that something like
```
R"sum(a$b)"
```
would be normal R syntax (looking up the `b` field of `a`, but
```
R"sum($b)"
```
would insert the Julia object `b` into the expression.

**Comment by dmbates** [comment]
Any further progress, Simon?  I am running a workshop on "Julia for Statisticians" where RCall is extremely useful and would like to give a general prescription of

R"""
# your R code here
"""

**Comment by simonbyrne** [comment]
Not yet. I'm looking at some other RCall improvements, so I might try to see what I can do in the next few days.

**Comment by dmbates** [comment]
@simonbyrne Let me know if I can help in some way.

Would it be worthwhile dropping support for v0.3 in addition to other changes?  That could simplify the inline documentation and allow for removal of some of the calls to `@compat`

**Comment by simonbyrne** [comment]
I was going to do that. I also want to get precompilation working.
