### ISSUE TITLE
RCall stack smashing detected - Julia 0.4.3

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaStats/RCall.jl#84]
Reproduction below - is this an RCall or Julia issue ? 

```
julia> using RCall
julia> @time for( i in 1:1000 ) rcopy( string("c(", join( [rand() * j for j in  1:1000], "," ), ")")) end
  1.414018 seconds (6.17 M allocations: 285.378 MB, 2.55% gc time)

julia> @time for( i in 1:1000 ) rcopy( string("c(", join( [rand() * j for j in  1:1000], "," ), ")")) end
  1.300732 seconds (6.05 M allocations: 280.270 MB, 2.04% gc time)

julia> @time for( i in 1:1000 ) rcopy( string("c(", join( [rand() * j for j in  1:1000], "," ), ")")) end
*** stack smashing detected ***: julia terminated

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f8e142e8394)
__fortify_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
__fortify_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f8c00b22641)
unknown function (ip: (nil))
Aborted (core dumped)
```

**Comment by randy3k** [comment]
I guess it was caused by insufficient memory in R, it works fine if we run `gc()` regularly.

```julia
using RCall
for( i in 1:1000 ) 
    println(i)
    rcall(:gc)
    rcopy(string("c(", join( [rand() * j for j in  1:1000], "," ), ")"))
end
```

Please note that you created a long string and it is passed to R to be parsed and evaluated. R needs to keep it temporarily. If a lot of such variables are creating at the same time, it causes R to break.

I also wonder why `gc()` is not fired automatically if there is not sufficient memory.

**Comment by simonbyrne** [comment]
Hmm, that is odd.

**Comment by mdcfrancis** [comment]
This is the simplest reproduction, in the real case we have a collection of fairly large R object which we are calling from Julia with a map. Every so often it crashes, it does look like it may be a gc issue.

**Comment by randy3k** [comment]
It seems that dc7975e0c2e399f0a89dab0337a51d5dd6a03b9d fixes this. I think it is caused by [wrongly](https://github.com/JuliaStats/RCall.jl/commit/dc7975e0c2e399f0a89dab0337a51d5dd6a03b9d?diff=unified#diff-519a35d79cd48fa67949c14cb6ad8b8bR51) "gc" the string variable since it is unprotected.

**Comment by randy3k** [comment]
@mdcfrancis 
could you confirm that it is fixed?

**Comment by simonbyrne** [comment]
Please reopen if this is still an issue.

**Comment by mdcfrancis** [comment]
Sorry for not replying - yes I see that this fixed this case.
