### ISSUE TITLE
Extracting values of S4 classes

### ISSUE THREAD

**Issue by abhinavuttam** [JuliaStats/RCall.jl#92]
In R, S4 classes like "ca.jo" have values which are extracted within R by the @ symbol.

Example: in R I would call jh@cval or jh@teststat etc. to get the function results.  How can this be accomplished in Julia?

Thanks,

` a = rand(100);
b = rand(100);
jh = rcall(symbol("ca.jo") , DataFrame(a=a,b=b);
`

**Comment by abhinavuttam** [comment]
I believe "slot" method works in this case.  But if relevant method is not available for an object, is there a way to access those values from R.

`rcall(:slot, jh,"cval")
`

**Comment by randy3k** [comment]
It would be also done by `getAttrib` and `setAttrib!` commands.

```r
using RCall
using DataFrames

myTrack = reval("""
    setClass("track", representation(x="numeric", y="numeric"))
     new("track", x = -4:4, y = exp(-4:4))
""")

getAttrib(myTrack, "x")
setAttrib!(myTrack, "x", 1:8)
```

**Comment by abhinavuttam** [comment]
Thanks Randy.

**Comment by randy3k** [comment]
I have just added the getter and setter for s4 objects. Now it is possible to do
```julia
myTrack[:x]
myTrack[:x] = 1:8
```
