### ISSUE TITLE
Forbidden the mixing of two language?

### ISSUE THREAD

**Issue by panlanfeng** [JuliaStats/RCall.jl#96]
Using the most recent `RCall` I can do the following

~~~julia
using RCall
@rlibrary stats
@rlibrary graphics
#This works
plot(rnorm(10), randn(10), xlab="",ylab="", var"type"="l")

#This does not
plot(rnorm(10), randn(10), xlab="",ylab="", type="l")
~~~

While I was shocked by the capability of this package, I slightly worry about the robustness.
I mixed the two language together and it can run if there is no confusing in both languages.
However if there is, such as `type` is a reserved keyword in julia, it causes problem and it is hard to debug. 

So should we forbidden the mixing of two languages? 
Such as only allow R expression and interpret every word as R expression in this kind of usage; always use `@R_str` to allow for julia expression. (I am not sure if we can interpret `type` as a R expression.)

What is your plan?

**Comment by simonbyrne** [comment]
I'm not sure there is a concrete plan yet: we've basically been trying various approaches to see what works well. As you've pointed out, there are some problems with `@rimport`/`@rlibrary`. The `@R_str` macro is looking promising, but this is quite a recent addition so hasn't been well tested yet.

Ultimately when trying to do stuff like this there are always going to be weird edge cases, especially with R which has such crazy semantics.

**Comment by panlanfeng** [comment]
Just realized, using another crazy "feature" of R, the following also works

~~~julia
plot(rnorm(10), randn(10), xlab="",ylab="", typ="l")
~~~

**Comment by dmbates** [comment]
@panlanfeng That was called "partial matching" of argument names (see the `R` function `pmatch`) and was inherited from the `S` language.  In the early days we didn't have argument name completion or even line editing within the `R` REPL so avoiding retyping long names many times was important.  It is one of those things, like lazy evaluation, that seemed like a good idea at the time and now makes you think, "What?"

At present, and I expect for some time to come, the way I use the RCall package is just
```
R"""
... # write your R code here
"""
```

I agree with you that there is just too much potential for namespace collision when using `@rlibrary`

**Comment by panlanfeng** [comment]
I like the idea of "partial matching" and I use it happily in R.

Writing R code directly in julia is just so cool and I hope it can work in some safer way. 
Maybe we can do something like
~~~julia
dat = randn(100)
@R plot(x = dat, xlab="", ylab="", type="l")
~~~
which only translates data variables but leave everything else as R expression.
But it might be hard to tell julia to ignore the a reserved  keyword like "type". 

It is up to you guys. `R"plot(x=$dat)"` is also cool.

**Comment by randy3k** [comment]
I was trying to handle lazy evaluation in #42, but so far, there is not much success. I agree with @dmbates that, currently, the best way to run R commands is to use `@R_str`, though syntax highlighting is generally not possible if you write R code using  `@R_str`.
